image: Visual Studio 2017

skip_branch_with_pr: true
  
before_build:
  - nuget restore HttpPostSerializer.sln
    
dotnet_csproj:
  patch: true
  file: src\HttpPostSerializer\HttpPostSerializer.csproj
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  
build:
    project: HttpPostSerializer.sln
    publish_nuget: true
    publish_nuget_symbols: false
    verbosity: minimal

deploy:
 - provider: NuGet
   api_key:
     secure: swbVO/mLDF9LqZnkMZJ2YDtPkdPyjQxrqLk79gYbBaT/fbhkmEGPEpuYZqyor9RK
   artifact: /.*\.nupkg/
   on:
     branch: master